spring:

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 5000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
